version: '3.7'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: coupondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
    ports:
      - "5432:5432"
    networks:
      - coupon-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - coupon-network

networks:
  coupon-network:
    driver: bridge
